version: '3.4'

services:
  application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - "DatabaseSettings:ConnectionString=Server=postgres;Port=5432;Database=RedisPostgresApiDb;User Id=postgres;Password=admin"
    ports:
      - "8000:80"
    depends_on:
     - postgres  

  postgres:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=RedisPostgresApiDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  pgadmin:
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    